##### 1.Sayılardan oluşan bir boyutlu array oluşturun. Arrayi oluştururken sayıların veri tipini integer olarak belirtelim.

Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakalım.

In [1]:
import numpy as np

In [2]:
a=np.array([3,5,13,15], dtype="int")
a

array([ 3,  5, 13, 15])

In [3]:
print(a.ndim)

1


In [4]:
print(a.size)

4


##### 2. Aşağıda verilen iki boyutlu ve üç boyutlu arrayi oluşturalım. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşalım. 

İki boyutlu array:
[[1,2,6,7],
 [4,3,9,5]]

Üç boyutlu array:
[[[7,5,14],[21,8,11]],
 [[8,6,20],[14,3,9]]]

 

In [5]:
iki_boyutlu = np.array([[1,2,6,7],[4,3,9,5]])
iki_boyutlu

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [6]:
üç_boyutlu = np.array([[[7,5,14],[21,8,11]], [[8,6,20],[14,3,9]]])
üç_boyutlu

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [7]:
print(iki_boyutlu.ndim)
print(üç_boyutlu.ndim)

2
3


In [8]:
print(iki_boyutlu.size)
print(üç_boyutlu.size)

8
12


In [9]:
np.shape(iki_boyutlu)

(2, 4)

In [10]:
np.shape(üç_boyutlu)

(2, 2, 3)

##### 3. İstenilen elamanlara ulaşmak için arrayler üzerinde indexleme işlemi yapalım

In [11]:
#İki boyutlu arraydaki 2 elemanına ulaşalım
iki_boyutlu[0,1]

2

In [12]:
#İki boyutlu arraydaki 7 elemanına ulaşalım
iki_boyutlu[0,3]

7

In [13]:
#Üç boyutlu arraydaki 9 elemanına ulaşalım
üç_boyutlu[1,1,2]

9

In [14]:
#Üç boyutlu arraydaki 5 elemanına ulaşalım
üç_boyutlu[0,0,1]

5

##### 4. Arrayler üzerinde slicing işlemi uygulayalım.

In [15]:
iki_boyutlu

array([[1, 2, 6, 7],
       [4, 3, 9, 5]])

In [16]:
#İki boyutlu arraydaki 2,6 elemanlarına ulaşalım
iki_boyutlu[0,1:3]

array([2, 6])

In [17]:
#İki boyutlu arraydaki 3,9,5 elemanlarına ulaşalım
iki_boyutlu[1,1:4]

array([3, 9, 5])

In [18]:
üç_boyutlu

array([[[ 7,  5, 14],
        [21,  8, 11]],

       [[ 8,  6, 20],
        [14,  3,  9]]])

In [19]:
#Üç boyutlu arraydaki 21,8,11 elemanlarına ulaşalım
üç_boyutlu[0,1,:]

array([21,  8, 11])

In [20]:
#Üç boyutlu arraydaki 6,20 elemanlarına ulaşalım
üç_boyutlu[1,0,1:3]

array([ 6, 20])

##### 5. 5 satır 3 sütunluk sıfırlardan ve birlerden oluşan iki tane iki boyutlu array oluşturalım. Bu arrayleri satır ve sütun bazında birleştirelim.

In [21]:
x=np.zeros((5,3),dtype="int")
x

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
y=np.ones((5,3),dtype="int")
y

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [23]:
np.concatenate([x,y],axis=0)   #satır bazında birleştirme

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [24]:
np.concatenate([x,y],axis=1)   #sütun bazında birleştirme

array([[0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1],
       [0, 0, 0, 1, 1, 1]])